### PR TITLE
Prefix `www` urls with `https://`

### PR DESCRIPTION
**Pull request by smithbm2316**
Fixes follow-up issue discussed in #7, until I read the codebase I did not realize that this would be such a simple fix 😆

### CODE REVIEW

**Comment by smithbm2316** [comment]
I will work on getting the tests to pass later tonight! Looks like I had a bit of an oversight here on how simple it would be

**Review by axieax — CHANGES_REQUESTED** [review]
Could you replace the empty string in line 28 with the default_prefix instead ("https://"). Captures is meant to be a table (map) from url ending pattern -> prefix (protocol). Sorry for my incorrect type annotation on line 15.

**Comment by axieax** [comment]
It's expected that the tests fail because they longer account for the default_prefix. Could you also make `default_prefix` a config option, so we are able to test it using a `before_each` setup.

**Comment by smithbm2316** [comment]
@axieax is the latest commit what you were thinking? I probably should've just let you handle it since it seems like you knew exactly what you wanted to change 😆

**Comment by axieax** [comment]
That's exactly what I wanted thanks ahaha!
I've updated the tests as well from my end, not too sure how I can add commits to this PR though.

**Comment by smithbm2316** [comment]
oh yeah...i can give you push access to my fork probably and then you can just add a commit to `main` there. give me a sec

**Comment by axieax** [comment]
Thanks for that! I've added the commit now. If you're happy with the changes, I'll merge it in :))

**Review by axieax — APPROVED** [review]

**Comment by smithbm2316** [comment]
Yeah! Looks good to me 😄

**Comment by axieax** [comment]
Tysm for the help :))

**Pull request merged**
