### PR TITLE
feat: support Windows

### LINKED ISSUE #41: Add windows support
Minimal plugin but useful!
I was researching if there is a command for opening a url on windows and I found `start`. eg: `start https://github.com`. this will open that url with the system's default browser

### PR DESCRIPTION
**Pull request by lopi-py**
closes #41

### CODE REVIEW

**Comment by axieax** [comment]
From memory, 'start' for the windows condition should be enough (without the /C hack), so a two line change would suffice for this feature - another case for os:match("Windows") -> calls start.

**Comment by lopi-py** [comment]
I tried but it doesnt work
image
also `executable("start")` returns 0 which means false

**Review by axieax — CHANGES_REQUESTED** [review]

**Comment by axieax** [comment]
> I tried but it doesnt work
> 
> image
> 
> also `executable("start")` returns 0 which means false

Are you using WSL or Windows?

**Comment by lopi-py** [comment]
Windows, on WSL xdg-open is used

**Comment by axieax** [comment]
Just curious are you using the raw nvim release binary or a graphical client?

**Comment by lopi-py** [comment]
Now I'm using raw neovim but usually I use neovide

**Comment by axieax** [comment]
Ok I've refactored a few things. Could you please add me as a collaborator to your fork? Just want to test a quick thing before merging :))

**Comment by lopi-py** [comment]
Done

**Comment by axieax** [comment]
Can you have a check if this works now :))

**Comment by lopi-py** [comment]
it works

**Comment by axieax** [comment]
Perfect! Thanks for confirming :))

**Review by axieax — APPROVED** [review]

**Pull request merged**
