### PR TITLE
fix(helper/extract-plugin): fix lazy boundary

### PR DESCRIPTION
**Pull request by xlboy**
When a local plugin is used in `lazy.nvim`, the **plugins** obtained from `lazy.nvim` will not contain the `url` field, thus causing boundary problems.

### CODE REVIEW

**Comment by xlboy** [comment]
image

Regarding the `lazy-plugins` found in the search, if a **local plugin** is encountered, i.e.,

```lua
local local_lazy_plugin_spec = {
    dir = "~/Desktops/nvim-dev-plugins/xxx"
}
```
then the `plugins` related to this local one will not contain a `url` field.

**Comment by axieax** [comment]
Great pickup and thanks for the PR! Could you please address the lint issues to make the pipeline happy :D

Also, perhaps a `url` field can be manually added for local plugins so `urlview` can display them :p

**Comment by xlboy** [comment]
> Great pickup and thanks for the PR! Could you please address the lint issues to make the pipeline happy :D

I'm sorry.
> Also, perhaps a `url` field can be manually added for local plugins so `urlview` can display them :p

OK :)

**Review by axieax — APPROVED** [review]
Oh you're good, thanks for making the changes!

**Pull request merged**
